### ISSUE TITLE
Support referring to distributed slices declared in sub-modules

### ISSUE THREAD

**Issue by daboross** [dtolnay/linkme#18]
As far as I can tell, if a distributed slice is declared anywhere beside the crate root, the element macro can't be used from any other scope.

Here's a simple example, adapted from the `distributed_slice` test:

```rust
mod declaration {
    use linkme::distributed_slice;

    #[distributed_slice]
    pub static SLICE: [i32] = [..];
}

mod usage {
    use linkme::distributed_slice;

    #[distributed_slice(crate::declaration::SLICE)]
    pub static N: i32 = 9;
}

mod alt_usage {
    use linkme::distributed_slice;

    use crate::declaration::SLICE;

    #[distributed_slice(SLICE)]
    pub static N: i32 = 9;
}
```

Both `usage` and `alt_usage` fail to compile:

```
$ cargo test
   Compiling linkmetest v0.1.0 (/home/daboross/linkmetest)
error[E0433]: failed to resolve: could not find `SLICE` in `declaration`
  --> src/main.rs:11:45
   |
11 |     #[distributed_slice(crate::declaration::SLICE)]
   |                                             ^^^^^ could not find `SLICE` in `declaration`

error: cannot find macro `SLICE!` in this scope
  --> src/main.rs:20:25
   |
20 |     #[distributed_slice(SLICE)]
   |                         ^^^^^
   |
   = help: have you added the `#[macro_use]` on the module/import?

warning: unused import: `crate::declaration::SLICE`
  --> src/main.rs:18:9
   |
18 |     use crate::declaration::SLICE;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `linkmetest`.

To learn more, run the command again with --verbose.
```

I'm assuming this case simply isn't supported. But since this seems potentially quite useful, I'm opening this issue to track it.

---

I believe the cause for this is the usage of `macro_rules!` macros, and the fact that when exported using `#[macro_export]`, they're always exported from the crate root, regardless of the module they're declared in. This works as long as the static is also exported from the crate root, but as soon as it's declared in a sub-module, it's hard to make this work.

**Comment by arcnmx** [comment]
Small note:

This does work if you `use` both `crate::SLICE` (the macro) and `crate::declaration::SLICE` (the static). Which is kind of hard to do unless `usage` and `declaration` happen to be in different crates, because referring to a `macro_export` by path in the same crate is difficult? But you can make it work, like say...

```rust
mod declaration {
    #[macro_use]
    mod scope {
        #[linkme::distributed_slice]
        pub static SLICE: [i32] = [..];
    }

    pub use scope::*;
    pub use SLICE;
}

mod usage {
    #[linkme::distributed_slice(crate::declaration::SLICE)]
    pub static N: i32 = 9;
}
```

**Comment by dtolnay** [comment]
We should fix #[distributed_slice] to generate the right reexports like that. Want to send a PR?

**Comment by azriel91** [comment]
Hey, really appreciate that all of you took the time to figure this out and implement a fix :bowing_man:.

Also very grateful to @dtolnay for:

* Authoring so many crates that do *difficult* things
* So much effort is put into ergonomics (usage, errors) and documentation, in every crate
* Responding so quickly across many repos
