### ISSUE TITLE
Feature request: support anonymous slice element.

### ISSUE THREAD

**Issue by crlf0710** [dtolnay/linkme#30]
I'm trying to write a macro that put elements into a distribute_slice. One hard thing is that i have to name the individual items... 

I feel it would be more convenient if using _ as the name of anonymous slice element is supported (distribute_slice(XYZ) can replace it with whatever name it feels best i think).

**Comment by dtolnay** [comment]
This would be on the language to permit `static _` as valid syntax; it was decided against in https://github.com/rust-lang/rust/issues/54912.

**Comment by dtolnay** [comment]
To avoid naming elements from the macro you can make your macro expand to:

```rust
const _: () = {
    #[distributed_slice(...)]
    static __: Type = value;
};
```

**Comment by crlf0710** [comment]
OK, great to know, thanks!
