### ISSUE TITLE
Cortex-M build is failing: 0 vs 3

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/linkme#40]
```console
     Running `qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel /home/runner/work/linkme/linkme/target/thumbv7m-none-eabi/release/cortex-m-linkme-test`
panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `3`', tests/cortex/src/main.rs:25:5
```

This appears to be a regression from nightly-2021-08-21 to nightly-2021-08-22. A couple older nightlies I spot checked all work, whereas 2021-08-22 fails consistently.

**Comment by dtolnay** [comment]
Per `cargo-bisect-rustc --start 2021-08-21 --end 2021-08-22 --target thumbv7m-none-eabi -- run --release`, this bisects to https://github.com/rust-lang/rust/pull/87570.

**Comment by yfblock** [comment]
I used #[used(linker)] instead of #[used] and passed the `cortex` test. But need to add #![feature(used with arg)]. I don't know if it is a efficient way.

**Comment by dtolnay** [comment]
It didn't work when I tried it. The Cortex-M job fails the same way with `#[used(linker)]` as it does with just `#[used]`. See #55. @yfblock could you make a PR showing exactly what change you made to make the cortex test succeed?

**Comment by yfblock** [comment]
@dtolnay Very strange. I can't reproduce it anywhere else, not just my computer or github CodeSpace. It only seems to happen on github ci.
![github_codespace](https://user-images.githubusercontent.com/14835777/197956060-135ebeb7-a905-4b85-8d02-58d147fce87a.png)
![image](https://user-images.githubusercontent.com/14835777/197957937-f1222f2c-c398-466f-8ca6-b530c51582ab.png)

https://github.com/yfblock/linkme/tree/temp

What I did was modify the "memory.x" file according to your pr [https://github.com/dtolnay/linkme/pull/55](https://github.com/dtolnay/linkme/pull/55).

**Comment by yfblock** [comment]
I try to remove linkme related code from `cortex` test. But still got errors when pushing.
