### ISSUE TITLE
Opt-out of duplicate check

### ISSUE THREAD

**Issue by oberrich** [dtolnay/linkme#99]
Based on the discussion in #3, it seems that when you declare a `distributed_slice` within a library it automatically gets prefixed with the crate's name, thus the duplicate check shouldn't be necessary.
It appears however that the inclusion of multiple semvers of the crate can result in duplicate declarations.

Unfortunately, the duplicate check has two unwanted consequences: an extra `.linkm2_` section as well as a potential `panic!`.
I tried adding `println!("cargo:rustc-link-arg-bins=/MERGE:.linkme_=.data,.linkm2_=.rdata")` to the `build.rs` script in an attempt to get rid of the section(s), but that didn't seem to have any effect.

It would be helpful to have a feature flag, like `no_dupcheck`, to conditionally opt-out of the duplicate checks introduced in #53 when creating a `release` build.

Also, is there any way to prevent multiple semvers from causing duplicate slices in the first place?

**Comment by gmoshkin** [comment]
We also encountered this problem in github.com/picodata/tarantool-module. We use distributed slices for a couple of our features, which is really helpful, thanks a lot for the great work you're doing on the project! But after updating to latest version we started having issues with multiple dependencies which all use our base library. The opt-out feature would help us out a ton

**Comment by dtolnay** [comment]
The duplicate check is needed for soundness. I am not going to add a feature that makes the crate unsound. Do you have a different suggestion?

Instead of redeclaring a different distributed slice in every different semver version of your library, you need to move it into a single dependency that is reused (maybe re-exported) by your different versions.

**Comment by gmoshkin** [comment]
> The duplicate check is needed for soundness. I am not going to add a feature that makes the crate unsound.

That's a shame. I wish the language wasn't so strict that all the good features must be removed due to unsoundness. Thanks for the quick response anyways! And thanks again for all the work you're doing!

**Comment by funbringer** [comment]
> The duplicate check is needed for soundness. I am not going to add a feature that makes the crate unsound. Do you have a different suggestion?

What if we could include a mangled type name into the section name somehow? Then we'd be able to have separate sections for incompatible types.

**Comment by funbringer** [comment]
> Instead of redeclaring a different distributed slice in every different semver version of your library, you need to move it into a single dependency that is reused (maybe re-exported) by your different versions.

That sounds great and all, but this take is short sighted due to multiple versions of the same (transitive) dependency emerging every time somebody tinkers with deps in Cargo.toml. Just saying.
